export MONGO_HOST=127.0.0.1
export MONGO_PORT=27017
export LDAP_HOST=127.0.0.1
export LDAP_PORT=389
export LDAP_ADMIN_USER=test-user
export LDAP_ADMIN_PASSWORD=hogehoge
export LDAP_BIND_DN="ou=People,dc=example,dc=com"
export SMTP_HOST=127.0.0.1
export MAIL_FROM_ADDR="test@example.local"
